-- https://www.hackerrank.com/challenges/the-report

SELECT S.NAME, G.GRADE, S.MARKS
FROM STUDENTS S
INNER JOIN GRADES G ON S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK
WHERE G.GRADE > 7
ORDER BY G.GRADE DESC, NAME;

SELECT "NULL", G.GRADE, S.MARKS
FROM STUDENTS S
INNER JOIN GRADES G ON S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK
WHERE G.GRADE <= 7
ORDER BY G.GRADE DESC, NAME;


-- Alternative much shorter solution:

SELECT IF(G.GRADE < 8, "NULL",NAME), G.GRADE, S.MARKS
FROM STUDENTS S
INNER JOIN GRADES G ON S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK
ORDER BY G.GRADE DESC, NAME;
